name: github-actions
on:
  workflow_dispatch:
  #schedule:
    #- cron: "*/10 0-12,21-23 * * *"
            #"*/10 2-10 * * 1-5" 12時〜20時、10分ごとに動作
env:  #環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
  CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
  E_MAIL: ${{secrets.E_MAIL}}
  GOOGLE_URL: ${{secrets.GOOGLE_URL}}
  PASSWORD: ${{secrets.PASSWORD}}
  LINE_NOTIFY: ${{secrets.LINE_NOTIFY}}
  LINE_NOTIFY_27: ${{secrets.LINE_NOTIFY_27}}

jobs:
  selenium:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install python-dotenv==0.19.2
          pip install selenium==3.141.0
          pip install tweepy==4.6.0
          pip install pillow==8.4.0
          pip install pydrive==1.3.1
          pip install opencv-python==4.5.5.64
          python schedule.py
